language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew upgrade cmake;
      brew install cmake python3;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pyenv global 3.7.1;
    fi
install:
  - pip3 install conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/conan/conan-center
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env:
        - CONFIG=Release

    - os: osx
      osx_image: xcode11.2
      env:
        - CONFIG=Debug

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CONFIG=Debug"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CONFIG=Release"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CONFIG=Debug"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CONFIG=Release"

script:
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTING=On
  - cmake --build .
  - ./bin/fea_unsigned_map_tests

notifications:
  email:
    on_success: never
    on_failure: always
