image:
  - Visual Studio 2017
platform:
  - x64
configuration:
  - Debug
  - Release
clone_folder: c:\projects\string_algorithm
before_build:
  - cmd: cd c:\projects\string_algorithm
  - cmd: mkdir build
  - cmd: cd build
  - cmd: ..\conan.bat
  - cmd: cmake .. -A x64 -DBUILD_TESTING=On
build:
  project: c:\projects\string_algorithm\build\string_algorithm.sln
  parallel: true
install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: cd ..
  - cmd: conan user
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: cd c:\projects\string_algorithm
test_script:
  - cmd: c:\projects\string_algorithm\build\bin\string_algorithm_tests.exe
